blank_issues_enabled: true
contact_links:
  - name: â“ Ask a question
    url: https://github.com/vueform/vueform/discussions/categories/questions
    about: Not sure about something? Receive an answer from Vueform team
  - name: ğŸš€ Feature Request
    url: https://github.com/vueform/vueform/discussions/categories/ideas
    about: Suggest a feature that will improve Vueform
  - name: ğŸ“š Learning Guide
    url: https://vueform.com/docs
    about: Learning material for Vueform
  - name: ğŸ“– API Reference
    url: https://vueform.com/reference
    about: Detailed reference for Vueform elements & components